export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>This is header of app</header>
        {children}
        <footer>This is footer of app</footer>
      </body>
    </html>
  );
}
